# Generated by Django 4.1.4 on 2022-12-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='banner',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
